### ISSUE TITLE
Miji_mod function 

### ISSUE THREAD

**Issue by dinisov** [YuToyoshima/RoiEdit3D#1]
Hello,

Thank you for providing this code. I am trying to use it but it calls a function named "Miji_mod" which is nowhere to be found.

Thank you,

Dinis

**Comment by YuToyoshima** [comment]
Thank you for using our code and letting us know of the problem.
I added the file you requested at /src/Miji_mod.m .
The code needs to be located as (Fiji_install_dir)/scripts/Miji_mod.m .
The Fiji with the Miji_mod.m can also be obtained from the figshare entry (http://dx.doi.org/10.6084/m9.figshare.8341088), as DatasetS5_code.7z.

Please let me know if you have any questions.
